[package]
name = "rrpc"
version = "0.1.0"
authors = ["Yushi OMOTE <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
error-chain = "0.12"
log = "0.4"
env_logger = "0.5"
tera = "0.11"

